name: Ash
favicon: null
layout_spectrum: 0.57674
typography_spectrum: 0.65
title: Ash Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f7f5eb'
    - '#c1c0bd'
    - '#4d4d4d'
    - '#859182'
  brandStrength: 0.5
  lightness: 0.23234377126209438
  saturation: 0.012030035490170121
  rhythmicContrast: 0.8021365394815803
purpose: []
